version: '3.8'

services:
  thumbnail_tester:
    build: .
    container_name: thumbnail_tester
    ports:
      - "9990:9990"
    depends_on:
      thumbnail-test-db:
        condition: service_healthy
    env_file:
      - .env
    restart: always
    volumes:
      - thumbnail_thumbnails:/app/thumbnails

  thumbnail-test-db:
    image: postgres:15
    container_name: thumbnail-test-db
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: thumbnailTester
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  thumbnail_thumbnails: